---
title: "Unit 1: Internal Validity"
subtitle: "Lecture Notes"
author: "Sean Sylvia, Ph.D."
date: January 16, 2025
format:
  html:
    toc: true
    toc-depth: 2
draft: false
---

# Introduction

Internal validity is the cornerstone of experimental design, crucial for establishing a causal relationship between treatment and outcome. It ensures that the observed effects in an experiment can be confidently attributed to the treatment rather than other confounding factors. This lecture explores the core principles and challenges of internal validity, including the role of randomization, exclusion restrictions, and the assignment mechanism. We also discuss practical applications and the complexities of ensuring compliance and observability in experimental settings.

# Learning Objectives

By the end of this lecture, you should be able to:

-   Understand the potential outcomes framework and its relevance in causal inference.
-   Explain the role of the assignment mechanism in maintaining internal validity.
-   Identify and address violations of key exclusion restrictions.
-   Distinguish between individual and average treatment effects.
-   Recognize the practical challenges of experimental design, including compliance and attrition.

# Key Concepts

-   The **Potential Outcomes Framework** is a useful way to understand causal inference.
    -   Causal inference is a missing data problem.
-   When an **Assignment Mechanism** is known and controlled by the researcher, we can recover internally valid estimates of causal effects.
-   Four key **Exclusion Restrictions** allow for experiments to estimate causal effects.
-   When these assumptions are not satisfied, we might not be able to recover the Average Treatment Effect (ATE), but can still learn certain things about causal effects.

# Concept Map

```{mermaid}
flowchart LR
    A["Difference in Conditional Expectations"]
    subgraph AssignmentMechanism [Assignment Mechanism]
        direction TB
        B1[Non-zero Probability Condition]
        B1 --> B2[Individualism]
        B2 --> B3[Unconfoundedness]
    end
    subgraph ExclusionRestrictions [Exclusion Restrictions]
    direction TB
        C1[SUTVA]
        C1 --> C2[Observability]
        C2 --> C3[Complete Compliance]
        C3 --> C4[Statistical Independence]
    end
A --> AssignmentMechanism --> ExclusionRestrictions --> D["Average Treatment Effect $$(\tau)$$"]
```

# Two scenarios

## Scenario 1

Suppose you are considering whether a new diet is linked to lower risk of inflammatory arthritis.

You observe that in a given sample: - A small fraction of individuals on the diet have inflammatory arthritis. - A large fraction of individuals not on the diet have inflammatory arthritis.

Based on this, you recommend that everyone pursue this new diet, but rates of inflammatory arthritis are unaffected.

What happened?

## Scenario 2

Consider a policy designed to reduce emergency room visits by offering free preventive care check-ups. Policymakers observed that communities with higher uptake of preventive care have fewer emergency visits. They implement the policy nationwide, expecting a significant reduction in emergency room visits. However, the policy shows no measurable impact.

What happened?

## Explanation

In each case, you were unable to see what would have happened to each individual if the alternative action had been applied.

In scenario 1, it could be that individuals who chose the diet may already have healthier lifestyles, including better exercise and reduced stress levels, which are known to reduce the risk of inflammatory arthritis. The observed differences may be due to these factors rather than the diet itself. Without randomization or controlling for confounding factors, you cannot attribute causality to the diet. The association observed may not reflect the causal effect of the diet.

In scenario 2, the observed association between preventive care and lower emergency room visits may reflect that communities with higher uptake of preventive care might already have better healthcare access, socioeconomic conditions, or health awareness—all factors that independently reduce emergency visits. Implementing the policy broadly, without considering these confounders, does not account for the variation in baseline conditions.

**The lack of this information is what prevents inference about causation from association.**

# The Potential Outcomes Framework

In our examples, the unseen information about each individual is the **counterfactual**. Without reasoning about the counterfactual, we can’t draw causal inferences—or worse, we draw the wrong causal inferences!

The potential outcomes model is a way to formally think about counterfactuals and causal inference.

Now let's formalize the Potential Outcomes Framework. Suppose there are two possible actions that can be assigned to an individual:

$$ 
D_{i,t} = 
\begin{cases} 
1 \text{ if "Treatment"} \\ 
0 \text{ if "Control"} 
\end{cases}
$$

$D_{i,t}$ is a binary variable defining treatment, where $i$ indexes an individual unit, such as a person.

What would this be for Scenario 1?

$$
D_{i,t} = 
\begin{cases} 
1 \text{ if placed on diet at time $t$} \\ 
0 \text{ if not placed on diet at time $t$} 
\end{cases}
$$

Now, *prior to treatment* there are two **Potential Outcomes** for an individual:

$$
Y_{i,t}^j =
\begin{cases} 
1 \text{ outcome if assigned to "Treatment" at time $t$} \\ 
0 \text{ outcome if assigned to "Control" at time $t$} 
\end{cases}
$$

$$
Y_{i,t}^j =
\begin{cases} 
1 \text{ health if placed on diet at time $t$} \\ 
0 \text{ health if not placed on diet at time $t$} 
\end{cases}
$$

In other words, there are two **Potential Outcomes** for an individual: one that would happen if they were assigned to the "Treatment" action ($Y_{i,t}^1$), and one if they were assigned to the "Control" action ($Y_{i,t}^0$).

The potential outcomes framework formalizes causal inference by defining two potential outcomes for each individual: ($Y_{i,t}^1$), the outcome if treated, and ($Y_{i,t}^0$), the outcome if untreated. Observing only one of these outcomes creates the **missing data problem**, central to causal inference.

Note that potential outcomes are different from realized outcomes. The potential outcomes are defined even *prior to treatment*. One an individual is assigned to treatment or control wee can then observe their realized outcome.

# Assignment Mechanism

The assignment mechanism is a crucial component of internal validity. It describes how an individual was assigned to receive treatment.

This could be due to a choice. Did a doctor choose to do it? Did the patient choose to do it? Did an algorithm choose to do it?

What is important here is **why** a particular choice was made. For instance, a doctor may choose to assign a patient to treatment based on their perception of treatment efficacy for that patient, or a patient may choose to assign themselves to treatment based on their perceived health benefits.

I.E. the assignmment may have been made based on someone, perception of the **individual treatment effect,** $\delta_{i}$:

$$
\delta_{i} = Y_{i,t}^1 - Y_{i,t}^0
$$

This individual's health outcome at time $t$ would then be determined by the switching equation:

$$
Y_{i} = D_{i}Y_{i,t}^1 + (1 - D_{i})Y_{i,t}^0
$$

where $Y_{i} = Y_{i,t}^1$ if $D_{i} = 1$ and $Y_{i} = Y_{i,t}^0$ if $D_{i} = 0$.

Because $D_{i}$ can only be 1 or 0, we cannot directly observe $delta_{i}$. This is the **Fundamental Problem of Causal Inference**: it is a problem of missing data.

In a population, we are interested in the population **average treatment effect (ATE)**, $E[\delta]$:

$$
\begin{align}
E[\delta] = E[\delta] = E[Y^1 - Y^0]
&= E[Y^1] - E[Y^0]
\end{align}
$$

But we cannot calculate this because $Y_{i}^1$ and $Y_{i}^0$ do not exist for the same individual $i$.

To see this more concretely, consider the following example: Assume a doctor sees patients, knows each person’s treatment effects, despite counterfactuals, and assigns treatment based on whether gains are positive or not.[^1]

[^1]: This example is adapted from Scott Cunninham's example in the Mixtape book.

Navigate to this shared spreadsheet and follow instructions.

[Perfect Doctor Exercise](https://docs.google.com/spreadsheets/d/1sC3PozGnqZXEVA9P1lRMpm8wp8w8huewaaSQIrUfY8Y/edit?gid=2087709103#gid=2087709103)

## Randomization

As we saw, the key source of bias arises from the assignment mechanism, or why a unit is assigned to treatment or control. Endogeneity can arise from units being assigned logically or based on percieved benefit, which is a function of their characteristics. There are two basic approaches to dealing with endogeneity:

1.  Model-based methods: Model the selection bias and then remove it mechanically
2.  Design-based methods: Use the design of the experiment and randomization to remove selection bias

**In randomized experiments, the assignment mechanism is controlled, and therefore known, by the researcher.** This is a unique and key difference from naturally-occuring data where the assignment mechanisms is neither controlled nor typically known. The experimental apporach is often referred to as the "gold standard" for estimating casual effects because randomization can be made to ensure that the assignment is independent of individual characteristics, eliminating bias.

To satisfy, the basic restrictions on the assignment mechanism for randomized experiments are:

### Three Conditions for a Valid Assignment Mechanism

1.  **Non-zero probability**: Each individual has a positive probability of being assigned to treatment or control.
2.  **Individualism**: Assignments are independent across individuals and do not depend on others' potential outcomes.
3.  **Unconfoundedness**: Treatment assignment is orthogonal to potential outcomes.

These conditions ensure that observed differences between groups are attributable to the treatment rather than pre-existing differences.

# Exclusion Restrictions

In an experiment, four key exclusion restrictions must be satisfied in order for results to be valid:

### Four Key Exclusion Restrictions

1.  **Observability**: Outcomes must be observed for all individuals; missing data can bias estimates.
2.  **Complete Compliance**: Those assigned to treatment must receive it, and those assigned to control must not.
3.  **Statistical Independence**: Treatment assignment is independent of potential outcomes.
4.  **Stable Unit Treatment Value Assumption (SUTVA)**: The treatment of one individual must not affect another’s outcomes.

When these conditions are met, researchers can confidently attribute differences in outcomes to the treatment. Violations can compromise the validity of results, so careful attention is needed to satisfy these conditions.

Several practical challenges can arise in an experiment that threaten internal validity by compromising teh satisfaction of these exclusion restrictions.

### Attrition

Attrition arises when participants drop out of a study, leading to missing data. This challenges the observability assumption and may bias results.

### Non-compliance

Non-compliance occurs when individuals assigned to treatment do not receive it or those assigned to control obtain the treatment. This can distort estimates of the treatment effect.

### Contamination or Spillovers

Contamination refers to instances where the assignment of one individual to treatment may have consequences for others, leading to bias in the estimated treatment effect.

Later in the course, we'll cover strategies for addressing these challenges in detail.