---
title: "Unit 1.2: Statistical Conclusion  Validity"
draft: false
---

## Unit Overview

-   Introduce statistical conclusion validity
-   Explore sources of uncertainty in experiments
-   Introduce hypothesis testing
-   Examine the role of statistical power in determining sample size
-   Use simulation techniques for power calculations and design assessments
-   Discuss multiple hypothesis testing and its implications

### Preparation

-   Read:
    -   [Wager Chapter 1](https://web.stanford.edu/~swager/causal_inf_book.pdf)
    -   [Declare Design Book: 5.1, 8.2, 10](https://book.declaredesign.org/declaration-diagnosis-redesign/crafting-data-strategy.html)
-   Listen:
    -   [Experimental Design and Multiple Hypothesis Testing Podcast](media/Experimental%20Design%20and%20Multiple%20Hypothesis%20Testing.mp3)

### Class

-   [Lecture: Statistical Conclusion Validity](/unit-1/lec-1-2.qmd)

### Labs

-   [Lab 2: Power Calculation by Simulation](/labs/lab-2-Power.qmd)
    -   Due by 11:59pm on Monday, February 17
    -   Submit on [Gradescope](https://www.gradescope.com/courses/1187218)
    -   Solutions: [lab-2-Power-sols.qmd](/labs/lab-2-Power-sols.qmd)