project:
  type: website
  output-dir: _site
  resources:
    - "quiz-generator/questions.js"

format:
  html:
    theme:
      light: [cosmo, style/hpm883.scss]
      dark: [cosmo, style/hpm883-dark.scss]
    filters:
      - shinylive
    mainfont: "Times New Roman"
    highlight-style: a11y-light
    include-in-header:
      - text: |
          <script src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
          <script src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script>
          <script src="https://unpkg.com/lodash@4.17.21/lodash.min.js"></script>

website:
  page-navigation: true
  title: "HPM 883 - Spring 2026"
  description: "Homepage for HPM 883: Advanced Quantitative Methods for Health Policy and Management - Spring 2026"
  site-url: https://hpm883.ssylvia.io
  repo-url: https://github.com/unc-hpm-quant/HPM883-Spring2026
  repo-actions: [edit, issue]

  draft-mode: unlinked
 
  sidebar:
    background: "#F5F5F5"
    logo: images/logo.png
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/unc-hpm-quant/HPM883-Spring2026
        text: "GitHub"
      - icon: code-square
        href: https://github.com/codespaces
        text: "Codespaces"
      - icon: life-preserver
        text: Support
        menu:
          - icon: person-raised-hand
            text: Office hours
            href: https://calendly.com/sean-sylvia/hpm-883-office-hours-1
          - icon: chat-dots-fill
            text: Course Discussions
            href: https://uncch.instructure.com/courses/108894/discussion_topics
          - icon: envelope-fill
            text: Anonymous Feedback
            href: https://unc.az1.qualtrics.com/jfe/form/SV_b3O2k8IV6hVLn9k
      - icon: slack
        href: https://hpm883.slack.com
        text: "Slack"
      - icon: file-check-fill
        text: "Canvas"
        menu:
          - icon: house-fill
            text: Course Home
            url: https://uncch.instructure.com/courses/108894
          - icon: megaphone-fill
            text: Announcements
            url: https://uncch.instructure.com/courses/108894/announcements
          - icon: file-arrow-up-fill
            text: Assignments
            url: https://uncch.instructure.com/courses/108894/assignments
          - icon: alphabet-uppercase
            text: Gradebook
            url: https://uncch.instructure.com/courses/108894/grades
    
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: "Home"
      - href: schedule.qmd
        text: "Schedule"
      - section: "Course Information"
        contents:
          - href: course-syllabus.qmd
            text: "Syllabus"
          - href: computing.qmd
            text: "Computing"
          - href: reproducible-research.qmd
            text: "Reproducibility Guide"
          - href: Resources/setup-guide.qmd
            text: "Setup Guide"
      - section: "Unit 0: Foundations"
        contents:
          - href: unit-0/unit-0-foundations-1.qmd
            text: "Session 0.1: Course Overview"
          - href: unit-0/unit-0-foundations-2.qmd
            text: "Session 0.2: Reproducible Research"
      - section: "Resources"
        contents:
          - href: resources.qmd
            text: "Reference Materials"


  page-footer:
    right: 'This page is built with [Quarto](https://quarto.org/).'
    left: "&copy; Copyright 2025-2026, Sean Sylvia"
    background: "#F5F5F5"

linkcolor: "#5D737E"
toc: true
code-copy: hover
code-link: true
code-overflow: wrap

execute:
  freeze: auto

editor: visual
